HOST: https://api.i-Ready.com/

--- Curriculum Associates Provisioning API v1 ---
---
Welcome to the Curriculum Associates [i-Ready](http://cainc.i-Ready.com/) Provisioning API documentation. Version 1.0 of our REST API for Provisioning is still under construction. Planned interfaces are documented below.

*i-Ready API Documentation version 0.9.0 - updated 7/11/13*

## Authentication  & Authorization

Each method call will be individually authenticated.
The authentication and authorization will be scoped to a single i-Ready district account.
Within the account the credentials may have further restrictions depending on the role assigned them.

### OAuth 2.0
The production deployment of the APIs will require all requests to include a valid OAuth 2.0 bearer token of authentication.

### Basic Authentication
In the i-Ready test & development environments the APIs will also accept http basic authentication credentials.

---

--
API Pattern - CRUD Operations
All the resources in the i-Ready Provising APIs share a common pattern for accessing them.

The API supports four type of opertions:

> Query, done via an http GET request.

> Create, done via an http POST request.

> Update, done via an http PUT request.

> Delete, done via an http DELETE request.
--
Query requests, http GET, will retrieve information about the resource identified by the URI.  The request body should be empty.  The request response will return data formatted in to two sections:

- status: Contains details about the success or failure of the request.  By default the status block in excluded if the request was successful, though it is shown below.
    - In debug environments the status block will include details about the account being accessed and, if applicable, exception data.
- data: The json representation of the resources requested; the schema of the data section is dependent on the type of object being accessed.

GET /<resource>
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": { ... }
}

Create requests, http POST, send a block of JSON that describes the new resource to be created.  The JSON must contain all required fields.
All read-only fields will be ignored by the server.

Create requests are always directed at the collection the new resource will be added to.  For example, a new Student will be created via a post to the /API/Students/ collection.

> Note: The i-Ready APIs will handle any properties not specified explicitly in the JSON passed to the POST operation as being null and will process the property accordingly.

The response will return a status and, if successful, data block.  The data block will return the details of the new resource including its identity.
POST /<resource>
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
{ ... }
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        ...,
        "id": "<unique-id>",
        "_links": {
            "self": { "href": "/<collection>/<unique-id>"},
            ...
        }
    }
}

Update requests, http PUT, send a block of JSON that describes the new values to be assigned to the resource.  The JSON uses the same schema as that used in the POST method and retrieved with the GET requests.
Read-only fields are ignored when processing the request.

> Note: The i-Ready APIs will handle any properties not specified explicitly in the JSON passed to the PUT operation as being null and will process the property accordingly.

The response to the update will contain a data block with the details of updated resource.
PUT /<resource>
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
{ ... }
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": { ... }
}

Delete requests, http DELETE, will delete the resource identified by the URI.  The request body should be empty.  The request response will contain a status block.
DELETE /<resource>
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    }
}

--
API Pattern - Hierarchy
All the resources in the i-Ready Provising APIs share a common pattern for accessing them.

> Note: The i-Ready API resources contain references to related resources.  These references should be used traverse between resources.  This section describes the hierarchical pattern used for organizing resources and resource collections.  This hierarchy is used consistantly but manual construction of paths based on this pattern will be prone to error.
--
Top level collections contain all the resources, of a given type within, the account.
All collections accept at least two, optional, parameters:

- limit: (Optional) The max number of items to retrieve.  A system limit of TBD will be imposed on all requests to collections.
- offset: (Optional) The index at which to start retrieving items.
- q: (Optional) A filter on the results returned by the query.  Filter strings take the form of <property>=<value>.  In the current release filters are supported on partnerId, ownerId, _links:school:href and _links:product:href.
    - E.g. Setting the _q_ parameter on the _/api/v1/classes_ resource to __links:school:href=/api/v1/schools/d120fb9c531f48ddaaab0733e1959054_ will return all classes in the school identified by __/api/v1/schools/d120fb9c531f48ddaaab0733e1959054_.
- count: (Optional) If set to 'true' will include total count of items in the collection; the default value is false.  The count value will adjust for any query filter parameters but ignores the limit and offset parameters.

The returned data section contains an array of returned items and properties about what was returned such as the limit and offset specified in the request.
GET /<top-level-collection>?limit=10&offset
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 10,
        "offset": 20,
        "_links": {
            "self": { "href": "/<top-level-collection>?limit=10&offset=20"}
            "next": { "href": "/<top-level-collection>?limit=10&offset=30"}
            "back": { "href": "/<top-level-collection>?limit=10&offset=10"}
        },
        "items": [
            { ... },
            { ... },
            { ... },
            { ... }
        ]
    }
}

Top level resources, E.g. Students, Classes, Teachers, etc, are identified as items within their corresponding top level collection.
GET /<top-level-collection>/{id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    }
}

Relationship collections are identified as resources within a top level resource.  For example all the classes assigned to a particular student will be accessed via a URI of the form:

> /api/students/{id}/classes/.
GET /<top-level-collection>/{id}/relationship-collection{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 20,
        "offset": 20,
        "_links": {
            "self": { "href": "/<top-level-collection>/{id}/<relationship-collection>?limit=20&offset=20"}
            "next": { "href": "/<top-level-collection>/{id}/<relationship-collection>?limit=20&offset=40"}
            "back": { "href": "/<top-level-collection>/{id}/<relationship-collection>?limit=20&offset=0"}
        },
        "items": [
            { ... },
            { ... },
            { ... },
            { ... }
        ]
    }
}

Relationship resources define the relationship between two top level resources.
Relationship objects contain references to the two top level resources and, optionally, additional properties used to describe the relationship.
GET /<top-level-collection>/{id}/relationship-collection/{relationship-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        ...,
        "_links": {
            "self": { "href": "/<top-level-collection>/{id}/<relationship-collection>/{relationship-id}"}
            "<first-type>": { "href": "/<top-level-collection>/{id}"}
            "<second-type>": { "href": "/<second-top-level-collection>/{id}"}
        }
    }
}

--
Account Resources
The following is a section of resources related to i-Ready Account resources.  There will be a single Account object per i-Ready account.

>### Account Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**academicYear**|string||read-only|no|XXXX-YYYY' where XXXX and YYYY are years; E.g. 2012-2013|
>|**accountScope**|string||read-only|no|School &#124; District|
>|**accountType**|string||read-only|no|'Current' For all production accounts.  Other values for test/development/pilot/etc accounts.|
>|**createdDate**|date||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**districtName**|string||read-only|no|string, length 100|
>|**id**|string|globally|read-only|no|string, length 32|
>|**state**|string||read-only|no|2 Character state code; e.g. CA.|
>|_**self**_|link|globally|read-only|no||


The Account resources are all read-only; Only http GET requests are supported.
--
Retrieve all of the accounts available to the calling i-Ready account. 
GET /api/v1/accounts{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    {
        "offset":"0",
        "limit":"200",
		"_links":{
			"self":{ "href":"/api/v1/accounts?offset=0&limit=200" }
			},
		"items":{
			"item":{
				"id":"{id}",
				"academicYear":"2012-2013",
				"accountScope":"District",
				"accountType":"Current",
				"districtName":"ACME District",
				"state":"CA",
				"createdDate":null,
				"_links":{
					"self":{ "href":"/api/v1/accounts/{id}" }
					}
				}
			}
		}
	}
}

Retrieve the details of a particular account.
GET /api/v1/accounts/{id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
   "data": {
		"item":{
			"id":"{id}",
			"academicYear":"2012-2013",
			"accountScope":"District",
			"accountType":"Current",
			"districtName":"ACME District",
			"state":"CA",
			"createdDate":null,
			"_links":{
				"self":{ "href":"/api/v1/accounts/{id}" }
				}
			}
		}
}

--
Product Resources
The following is a section of resources related to i-Ready Product resources.

>### Product Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**createdDate**|date||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**family**|string||read-only|no|string, length 35|
>|**id**|string|globally|read-only|no|string, length 32|
>|**minGradeLevel**|int||read-only|no|0-12|
>|**maxGradeLevel**|int||read-only|no|0-12|
>|**name**|string||read-only|no|string, length 64|
>|**subject**|string||read-only|no|Math &#124; ELA|
>|_**classes**_|link||read-only|no||
>|_**self**_|link|globally|read-only|no||

The Product resources are all read-only; Only http GET requests are supported.
--
Retrieve all of the products available to the calling i-Ready account. 
GET /api/v1/products{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/products?limit=2&offset=0"}
            "next": { "href": "/api/v1/products?limit=2&offset=2"}
        },
        "items": [
            {
               "createdDate": "2012-12-03T16:02:43Z",
               "family": "Diagnostic & Instruction",
               "id": "{first-id}",
               "name": "i-Ready Diagnostic & Instruction Math",
               "minGradeLevel":"0",
               "maxGradeLevel":"12",
               "subject": "Math",
               "_links":
               {
                   "self": "/products/{first-id}",
                   "classes": "/products/{first-id}/classes"
               }
            },
            {
               "createdDate": "2012-12-03T16:02:43Z",
               "family": "Diagnostic & Instruction",
               "id": "{second-id}",
               "name": "i-Ready Diagnostic & Instruction ELA",
               "minGradeLevel":"0",
               "maxGradeLevel":"12",
               "subject": "ELA",
               "_links":
               {
                   "self": "/products/{second-id}",
                   "classes": "/products/{second-id}/classes"
               }
            },
        ]
    }
}

Retrieve the details of a particular product.
GET /api/v1/products/{id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
   "data": {
       "createdDate": "2012-12-03T16:02:43Z",
       "family": "Diagnostic & Instruction",
       "id": "{id}",
       "minGradeLevel":"0",
       "maxGradeLevel":"12",
       "name": "i-Ready Diagnostic & Instruction Math",
       "subject": "Math",
       "_links":
       {
           "self": "/products/{id}",
           "classes": "/products/{id}/classes"
       }
    }
}

--
 Product/Class Resources
The following is a section of resources related to i-Ready Product/Class relationship resources.

The Product/Class resources are all read-only; Only http GET requests are supported.

>### Product/Class Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**createdDate**|date||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**id**|string|globally|read-only|no|string, length 32|
>|_**product**_|link||read-only|no||
>|_**class**_|link||read-only|no||
>|_**self**_|link|globally|read-only|no||

--
Retrieve the classes assigned to a particular product.
GET /api/v1/products/{id}/classes{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/products/{id}/classes?limit=2"}
            "next": { "href": "/api/v1/products/{id}/classes?limit=2&offset=2"}
        },
        "items": [
            {
                "createdDate": "2012-12-03T16:02:43Z",
                "id": "{first-reference-id}",
                "_links": {
                    "self": { "href": "/api/v1/products/{id}/classes/{first-reference-id}"}
                    "product": { "href": "/api/v1/products/{id}"}
                    "class": { "href": "/api/v1/classes/{first-class-id}"}
                }
            },
            {
                "createdDate": "2012-12-03T16:02:43Z",
                "id": "{second-reference-id}",
                "_links": {
                    "self": { "href": "/api/v1/products/{id}/classes/{second-reference-id}"}
                    "product": { "href": "/api/v1/products/{id}"}
                    "class": { "href": "/api/v1/classes/{second-class-id}"}
                }
            }
        ]
    }
}

Retrieve a particular product/class reference.
GET /api/v1/products/{id}/classes/{reference-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data":{
        "createdDate": "2012-12-03T16:02:43Z",
        "id": "{reference-id}",
        "_links": {
            "self": { "href": "/api/v1/products/{id}/classes/{reference-id}"}
            "product": { "href": "/api/v1/products/{id}"}
            "class": { "href": "/api/v1/classes/{class-id}"}
        }
    }
}

--
School Resources
The following is a section of resources related to i-Ready School resources.

>### School Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**districtName**|string||read-only|no|string, length 100|
>|**id**|string|globally|read-only|no|string, length 32|
>|**name**|string||read-only|no|string, length 100|
>|**ncesId**|string||read-only|no|string, length 12|
>|**state**|string||read-only|no|*us-state-abreviation*|
>|_**classes**_|link||read-only|no||
>|_**self**_|link|globally|read-only|no||
>|_**students**_|link||read-only|no||
>|_**teachers**_|link||read-only|no||

The School resources are all read-only; Only http GET requests are supported.
--
Retrieve all of the schools in the i-Ready account. 
GET /api/v1/schools{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/schools?limit=2&offset=0"}
            "next": { "href": "/api/v1/schools?limit=2&offset=2"}
        },
        "items": [
            {
                "id": "{first-id}",
                "name": "Harrington Elementary School",
                "districtName": "oh-9-26",
                "ncesId": null,
                "state": "OH",
               "_links":
               {
                   "self": "/schools/{first-id}",
                   "classes": "/schools/{first-id}/classes"
                   "students": "/schools/{first-id}/students"
                   "teachers": "/schools/{first-id}/teachers"
               }
            },
            {
                "id": "{second-id}",
                "name": "Lincoln Middle School",
                "districtName": "oh-9-26",
                "ncesId": "062069004673",
               "_links":
               {
                   "self": "/schools/{second-id}",
                   "classes": "/schools/{second-id}/classes"
                   "students": "/schools/{second-id}/students"
                   "teachers": "/schools/{second-id}/teachers"
               }
            },
        ]
    }
}

Retrieve the details of a particular school.
GET /api/v1/schools/{id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
   "data": {
        "id": "{id}",
        "name": "Harrington Elementary School",
        "districtName": "oh-9-26",
        "ncesId": "062069004673",
        "state": "OH",
       "_links":
       {
           "self": "/schools/{id}",
           "classes": "/schools/{id}/classes"
           "students": "/schools/{id}/students"
           "teachers": "/schools/{id}/teachers"
       }
    }
}

--
 School/Class Resources
The following is a section of resources related to i-Ready School/Class relationship resources.

The School/Class resources are all read-only; Only http GET requests are supported.

>### School/Class Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**createdDate**|date||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**id**|string|globally|read-only|no|string, length 32|
>|_**school**_|link||read-only|no||
>|_**class**_|link||read-only|no||
>|_**self**_|link|globally|read-only|no||

--
Retrieve the classes assigned to a particular school.
GET /api/v1/schools/{id}/classes{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/schools/{id}/classes?limit=2"}
            "next": { "href": "/api/v1/schools/{id}/classes?limit=2&offset=2"}
        },
        "items": [
            {
                "createdDate": "2012-12-03T16:02:43Z",
                "id": "{first-reference-id}",
                "_links": {
                    "self": { "href": "/api/v1/schools/{id}/classes/{first-reference-id}"}
                    "school": { "href": "/api/v1/schools/{id}"}
                    "class": { "href": "/api/v1/classes/{first-class-id}"}
                }
            },
            {
                "createdDate": "2012-12-03T16:02:43Z",
                "id": "{second-reference-id}",
                "_links": {
                    "self": { "href": "/api/v1/schools/{id}/classes/{second-reference-id}"}
                    "school": { "href": "/api/v1/schools/{id}"}
                    "class": { "href": "/api/v1/classes/{second-class-id}"}
                }
            }
        ]
    }
}

Retrieve a particular school/class reference.
GET /api/v1/schools/{id}/classes/{reference-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data":{
        "createdDate": "2012-12-03T16:02:43Z",
        "id": "{reference-id}",
        "_links": {
            "self": { "href": "/api/v1/schools/{id}/classes/{reference-id}"}
            "school": { "href": "/api/v1/schools/{id}"}
            "class": { "href": "/api/v1/classes/{class-id}"}
        }
    }
}

--
 School/Student Resources
The following is a section of resources related to i-Ready School/Student relationship resources.

The School/Student resources are all read-only; Only http GET requests are supported.

>### School/Student Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**createdDate**|date||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**id**|string|globally|read-only|no|string, length 32|
>|_**student**_|link||read-only|no||
>|_**school**_|link||read-only|no||
>|_**self**_|link|globally|read-only|no||

--
Retrieve the students assigned to a particular school.
GET /api/v1/schools/{id}/students{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/schools/{id}/students?limit=2"}
            "next": { "href": "/api/v1/schools/{id}/students?limit=2&offset=2"}
        },
        "items": [
            {
                "createdDate": "2012-12-03T16:02:43Z",
                "id": "{first-reference-id}",
                "_links": {
                    "self": { "href": "/api/v1/schools/{id}/students/{first-reference-id}"}
                    "school": { "href": "/api/v1/schools/{id}"}
                    "student": { "href": "/api/v1/students/{first-class-id}"}
                }
            },
            {
                "createdDate": "2012-12-03T16:02:43Z",
                "id": "{second-reference-id}",
                "_links": {
                    "self": { "href": "/api/v1/schools/{id}/students/{second-reference-id}"}
                    "school": { "href": "/api/v1/schools/{id}"}
                    "student": { "href": "/api/v1/students/{second-class-id}"}
                }
            }
        ]
    }
}

Retrieve a particular school/student reference.
GET /api/v1/schools/{id}/students/{reference-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data":{
        "createdDate": "2012-12-03T16:02:43Z",
        "id": "{reference-id}",
        "_links": {
            "self": { "href": "/api/v1/schools/{id}/students/{reference-id}"}
            "school": { "href": "/api/v1/schools/{id}"}
            "student": { "href": "/api/v1/students/{class-id}"}
        }
    }
}


--
 School/Teacher Resources
The following is a section of resources related to i-Ready School/Teacher relationship resources.

The School/Teacher resources are all read-only; Only http GET requests are supported.

>### School/Teacher Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**createdDate**|date||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**id**|string|globally|read-only|no|string, length 32|
>|_**teacher**_|link||read-only|no||
>|_**school**_|link||read-only|no||
>|_**self**_|link|globally|read-only|no||

--
Retrieve the teachers assigned to a particular school.
GET /api/v1/schools/{id}/teachers{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/schools/{id}/teachers?limit=2"}
            "next": { "href": "/api/v1/schools/{id}/teachers?limit=2&offset=2"}
        },
        "items": [
            {
                "createdDate": "2012-12-03T16:02:43Z",
                "id": "{first-reference-id}",
                "_links": {
                    "self": { "href": "/api/v1/schools/{id}/teachers/{first-reference-id}"}
                    "school": { "href": "/api/v1/schools/{id}"}
                    "teacher": { "href": "/api/v1/teachers/{first-class-id}"}
                }
            },
            {
                "createdDate": "2012-12-03T16:02:43Z",
                "id": "{second-reference-id}",
                "_links": {
                    "self": { "href": "/api/v1/schools/{id}/teachers/{second-reference-id}"}
                    "school": { "href": "/api/v1/schools/{id}"}
                    "teacher": { "href": "/api/v1/teachers/{second-class-id}"}
                }
            }
        ]
    }
}

Retrieve a particular school/teacher reference.
GET /api/v1/schools/{id}/teachers/{reference-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data":{
        "createdDate": "2012-12-03T16:02:43Z",
        "id": "{reference-id}",
        "_links": {
            "self": { "href": "/api/v1/schools/{id}/teachers/{reference-id}"}
            "school": { "href": "/api/v1/schools/{id}"}
            "teacher": { "href": "/api/v1/teachers/{class-id}"}
        }
    }
}

--
 School/Administrator Resources
 >**Administrator related resources have been removed from the initial release of the i-Ready APIs**
 
The following is a section of resources related to i-Ready School/Administrator relationship resources.

The School/Administrator resources are all read-only; Only http GET requests are supported.

>### School/Administrator Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**createdDate**|date||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**id**|string|globally|read-only|no|string, length 32|
>|_**administrator**_|link||read-only|no||
>|_**school**_|link||read-only|no||
>|_**self**_|link|globally|read-only|no||

--
Retrieve the administrators assigned to a particular school.
GET /api/v1/schools/{id}/administrators{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/schools/{id}/administrators?limit=2"}
            "next": { "href": "/api/v1/schools/{id}/administrators?limit=2&offset=2"}
        },
        "items": [
            {
                "createdDate": "2012-12-03T16:02:43Z",
                "id": "{first-reference-id}",
                "_links": {
                    "self": { "href": "/api/v1/schools/{id}/administrators/{first-reference-id}"}
                    "school": { "href": "/api/v1/schools/{id}"}
                    "administrator": { "href": "/api/v1/administrators/{first-class-id}"}
                }
            },
            {
                "createdDate": "2012-12-03T16:02:43Z",
                "id": "{second-reference-id}",
                "_links": {
                    "self": { "href": "/api/v1/schools/{id}/administrators/{second-reference-id}"}
                    "school": { "href": "/api/v1/schools/{id}"}
                    "administrator": { "href": "/api/v1/administrators/{second-class-id}"}
                }
            }
        ]
    }
}

Retrieve a particular school/administrator reference.
GET /api/v1/schools/{id}/administrators/{reference-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data":{
        "createdDate": "2012-12-03T16:02:43Z",
        "id": "{reference-id}",
        "_links": {
            "self": { "href": "/api/v1/schools/{id}/administrators/{reference-id}"}
            "school": { "href": "/api/v1/schools/{id}"}
            "administrator": { "href": "/api/v1/administrators/{class-id}"}
        }
    }
}

--
Class Resources
The following is a section of resources related to i-Ready Class resources.

>### Class Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**classCode**|string, length 10|||yes|string, length 10|
>|**createdDate**|string||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**gradeLevel**|int||create-time|no|0 - 12|
>|**id**|string|globally|read-only|no|string, length 32|
>|**location**|string|||yes|null &#124;string, length 255|
>|**name**|string|within academic-year/school/product||no|null &#124;string, length 255|
>|**ownerId**|string|within district*||yes|null &#124; string, length 64|
>|**partnerId**|string|within district*||yes|null &#124; string, length 64|
>|_**product**_|link||create-time|no||
>|_**school**_|link||create-time|no||
>|_**self**_|link|globally|read-only|no||
>|_**students**_|link||read-only|no||
>|_**teachers**_|link||read-only|no||
>
>The ownerId and partnerId values are unique per class per academic year; APIs only allow access to the current academic year.

Within a district account a class is uniquely identified by the combination of 4 properties; name, gradeLevel, school reference and product reference.

The class has an externalId property that can be set by the user.  This value must be unique within the district account or null.
--
Get all of the classes related to an i-Ready account.
GET /api/v1/classes{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/classes?limit=2&offset=0"}
            "next": { "href": "/api/v1/classes?limit=2&offset=2"}
        },
        "items": [
            {
               "id": "{first-class-id}",
               "name": "Grade K Class",
               "gradeLevel": "0",
               "location": "Room 201",
               "createdDate": "2012-08-17T14:56:43Z",
               "classCode": "CL012345",
               "ownerId": null,
               "partnerId": null,
               "_links":
               {
                   "school": { "href": "/api/v1/schools/{first-school-id}" },
                   "product": { "href": "/api/v1/products/{first-product-id}" },
                   "self": { "href": "/api/v1/classes/{first-class-id}" },
                   "students": { "href": "/api/v1/classes/{first-class-id}/students" },
                   "teachers": { "href": "/api/v1/classes/{first-class-id}/teachers" },
               }
           },
           {
               "id": "{second-class-id}",
               "name": "Hoosiers Grade 2 Class",
               "gradeLevel": "2",
               "location": "Room 305",
               "createdDate": "2012-08-17T14:56:43Z",
               "classCode": "CL012337",
               "ownerId": null,
               "partnerId": null,
               "_links":
               {
                   "school": { "href": "/api/v1/schools/{second-school-id}" },
                   "product": { "href": "/api/v1/products/{second-product-id}" },
                   "self": { "href": "/api/v1/classes/{second-class-id}" },
                   "students": { "href": "/api/v1/classes/{second-class-id}/students" },
                   "teachers": { "href": "/api/v1/classes/{second-class-id}/teachers" },
               }
           }
        ]
    }
}

Create a new Class.

When creating a new class the name, grade, school reference and product reference properties are required.

Read-only properties will be ignored.
POST /api/v1/classes
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{
    "id": null,
    "name": "Eagles - Grade 1",
    "gradeLevel": "1",
    "location": "Room 212",
    "createdDate": "null,
    "classCode": "CL012341",
    "ownerId": null,
    "partnerId": null,
    "_links":
    {
        "school": { "href": "/api/v1/schools/{school-id}" },
        "product": { "href": "/api/v1/products/{product-id}" }
        "self": null,
        "students": null,
        "teachers": null,
    }
}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{id}",
        "name": "Eagles - Grade 1",
        "gradeLevel": "1",
        "location": "Room 212",
        "createdDate": "2012-11-29T14:56:43Z",
        "classCode": "CL012341",
        "ownerId": null,
        "partnerId": null,
        "_links":
        {
            "school": { "href": "/api/v1/schools/{school-id}" },
            "product": { "href": "/api/v1/products/{product-id}" }
            "self": { "href": "/api/v1/classes/{id}" },
            "students": { "href": "/api/v1/classes/{id}/students" },
            "teachers": { "href": "/api/v1/classes/{id}/teachers" },
        }
    }
}

Get the details of a particular Class.
GET /api/v1/classes/{id}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{id}",
        "name": "Hoosiers Grade 2 Class",
        "gradeLevel": "2",
        "location": "Room 305",
        "createdDate": "2012-08-17T14:56:43Z",
        "classCode": "CL012341",
        "ownerId": null,
        "partnerId": null,
        "_links":
        {
            "school": { "href": "/api/v1/schools/{school-id}" },
            "product": { "href": "/api/v1/products/{product-id}" },
            "self": { "href": "/api/v1/classes/{id}" },
            "students": { "href": "/api/v1/classes/{id}/students" },
            "teachers": { "href": "/api/v1/classes/{id}/teachers" },
        }
    }
}

Update a particular class resource.

When updating the name, classCode and location values can be changed.  A class's school and product references cannot be modified after it had been created.

Read-only properties will be ignored.
PUT /api/v1/classes/{id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{
    "id": "{id}",
    "name": "Eagles - Grade 1",
    "gradeLevel": "1",
    "location": "Room 212",
    "createdDate": "2012-11-29T14:56:43Z",
    "classCode": "CL012341",
    "ownerId": null,
    "partnerId": "P0579",
    "_links":
    {
        "school": { "href": "/api/v1/schools/{school-id}" },
        "product": { "href": "/api/v1/products/{product-id}" }
        "self": { "href": "/api/v1/classes/{id}" },
        "students": { "href": "/api/v1/classes/{id}/students" },
        "teachers": { "href": "/api/v1/classes/{id}/teachers" },
    }
}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{id}",
        "name": "Eagles - Grade 1",
        "gradeLevel": "1",
        "location": "Room 212",
        "createdDate": "2012-11-29T14:56:43Z",
        "classCode": "CL012341",
        "ownerId": null,
        "partnerId": "P0579",
        "_links":
        {
            "school": { "href": "/api/v1/schools/{school-id}" },
            "product": { "href": "/api/v1/products/{product-id}" }
            "self": { "href": "/api/v1/classes/{id}" },
            "students": { "href": "/api/v1/classes/{id}/students" },
            "teachers": { "href": "/api/v1/classes/{id}/teachers" },
        }
    }
}

Delete a particular class.
DELETE /api/v1/classes/{id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    }
}

--
 Class/Student Resources
The following is a section of resources related to i-Ready Class/Student relationship resources.

>### Class/Student Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**createdDate**|date||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**id**|string|globally|read-only|no|string, length 32|
>|**ownerId**|string|within district||yes|null &#124; string, length 64|
>|**partnerId**|string|within district||yes|null &#124; string, length 64|
>|_**student**_|link||create-time|no||
>|_**class**_|link||create-time|no||
>|_**self**_|link|globally|read-only|no||

Restrictions:
> I-Ready restricts the number of classes a student can be assigned to based on the product and grade of the class.

> For i-Ready Diagnostic and Instruction each student can be assigned to one class per subject; In other words they can only be assigned one ELA class and one Math class.

> For i-Ready Screener and i-Ready Practice each student can be assigned to one class per subject per grade.  For example a student can be in one 3rd grade Math Practice class, one 3rd grade ELA Practice class and one 4th grade ELA Practice class.

--

Retrieve the students assigned to a particular class.
GET /api/v1/classes/{id}/students{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/classes/{id}/students?limit=2"}
            "next": { "href": "/api/v1/classes/{id}/students?limit=2&offset=2"}
        },
        "items": [
            {
                "id": "{first-relationship-id}",
                "createdDate": "2012-12-03T16:02:43Z",
                "ownerId": null,
                "partnerId": null,
                "_links": {
                    "self": { "href": "/api/v1/classes/{id}/students/{first-relationship-id}"}
                    "class": { "href": "/api/v1/classes/{id}"}
                    "student": { "href": "/api/v1/students/{first-student-id}"}
                }
            },
            {
                "id": "{second-relationship-id}",
                "createdDate": "2012-12-03T16:02:43Z",
                "ownerId": null,
                "partnerId": null,
                "_links": {
                    "self": { "href": "/api/v1/classes/{id}/students/{second-relationship-id}"}
                    "class": { "href": "/api/v1/classes/{id}"}
                    "student": { "href": "/api/v1/students/{second-student-id}"}
                }
            }
        ]
    }
}

Create a new class/student relationship.
POST /api/v1/classes/{id}/students
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{
    "id": null,
    "createdDate": null,
    "ownerId": null,
    "partnerId": null,
    "_links": {
        "self": null
        "class": { "href": "/api/v1/classes/{id}"}
        "student": { "href": "/api/v1/students/{student-id}"}
    }
}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{relationship-id}",
        "createdDate": "2012-12-03T16:02:43Z",
        "ownerId": null,
        "partnerId": null,
        "_links": {
            "self": { "href": "/api/v1/classes/{id}/students/{relationship-id}"}
            "class": { "href": "/api/v1/classes/{id}"}
            "student": { "href": "/api/v1/students/{student-id}"}
        }
    }
}

Retrieve a particular class/student relationship.
GET /api/v1/classes/{id}/students/{relationship-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data":{
        "id": "{relationship-id}",
        "createdDate": "2012-12-03T16:02:43Z",
        "ownerId": null,
        "partnerId": null,
        "_links": {
            "self": { "href": "/api/v1/classes/{id}/students/{relationship-id}"}
            "class": { "href": "/api/v1/classes/{id}"}
            "student": { "href": "/api/v1/students/{student-id}"}
        }
    }
}

Updating of class/student relationships is not supported.  If a student changes classes the old relationship should be deleted and a new one added.

PUT /api/v1/classes/{id}/students/{relationship-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 405
< Content-Type: application/json
{
    "status": {
        "httpCode": "405",
        "errorId": "C10004",
        "userMessage": "Operation not supported.",
        "detailsMessage": "Class/Student relationship resources can not be modified.",
        "apiVersion": "v1"
    }
}

Delete a particular class/student relationship.
DELETE /api/v1/classes/{id}/students/{relationship-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    }
}

--
 Class/Teacher Resources
The following is a section of resources related to i-Ready Class/Teacher relationship resources.

>### Class/Teacher Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**createdDate**|date||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**id**|string|globally|read-only|no|string, length 32|
>|**ownerId**|string|within district||yes|null &#124; string, length 64|
>|**partnerId**|string|within district||yes|null &#124; string, length 64|
>|_**teacher**_|link||create-time|no||
>|_**class**_|link||create-time|no||
>|_**self**_|link|globally|read-only|no||

Restrictions:
> I-Ready does not restrict either the number of teachers that can be assigned to a class or the number of classes that a teacher can be assigned to.

--
Retrieve the teachers assigned to a particular class.
GET /api/v1/classes/{id}/teachers{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/classes/{id}/teachers?limit=2"}
            "next": { "href": "/api/v1/classes/{id}/teachers?limit=2&offset=2"}
        },
        "items": [
            {
                "id": "{first-relationship-id}",
                "createdDate": "2012-12-03T16:02:43Z",
                "ownerId": null,
                "partnerId": null,
                "_links": {
                    "self": { "href": "/api/v1/classes/{id}/teachers/{first-relationship-id}"}
                    "class": { "href": "/api/v1/classes/{id}"}
                    "teacher": { "href": "/api/v1/teachers/{first-teacher-id}"}
                }
            },
            {
                "id": "{second-relationship-id}",
                "createdDate": "2012-12-03T16:02:43Z",
                "ownerId": null,
                "partnerId": null,
                "_links": {
                    "self": { "href": "/api/v1/classes/{id}/teachers/{second-relationship-id}"}
                    "class": { "href": "/api/v1/classes/{id}"}
                    "teacher": { "href": "/api/v1/teachers/{second-teacher-id}"}
                }
            }
        ]
    }
}

Create a new class/teacher relationship.
POST /api/v1/classes/{id}/teachers
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{
    "id": null,
    "createdDate": null,
    "ownerId": null,
    "partnerId": null,
    "_links": {
        "self": null
        "class": { "href": "/api/v1/classes/{id}"}
        "teacher": { "href": "/api/v1/teachers/{teacher-id}"}
    }
}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{relationship-id}",
        "createdDate": "2012-12-03T16:02:43Z",
        "ownerId": null,
        "partnerId": null,
        "_links": {
            "self": { "href": "/api/v1/classes/{id}/teachers/{relationship-id}"}
            "class": { "href": "/api/v1/classes/{id}"}
            "teacher": { "href": "/api/v1/teachers/{teacher-id}"}
        }
    }
}

Retrieve a particular class/teacher relationship.
GET /api/v1/classes/{id}/teachers/{relationship-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data":{
        "id": "{relationship-id}",
        "createdDate": "2012-12-03T16:02:43Z",
        "ownerId": null,
        "partnerId": null,
        "_links": {
            "self": { "href": "/api/v1/classes/{id}/teachers/{relationship-id}"}
            "class": { "href": "/api/v1/classes/{id}"}
            "teacher": { "href": "/api/v1/teachers/{teacher-id}"}
        }
    }
}

Updating of class/teacher relationships is not supported.  If a teacher changes classes the old relationship should be deleted and a new one added.
PUT /api/v1/classes/{id}/teachers/{relationship-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 405
< Content-Type: application/json
{
    "status": {
        "httpCode": "405",
        "errorId": "C10004",
        "userMessage": "Operation not supported.",
        "detailsMessage": "Class/Teacher relationship resources can not be modified.",
        "apiVersion": "v1"
    }
}

Delete a particular class/teacher relationship.
DELETE /api/v1/classes/{id}/teachers/{relationship-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    }
}


--
Student Resources
The following is a section of resources related to i-Ready Student resources.

Students are identified by their userName. The student's userName must by unique to all users within their distict account's state.

Additionally the student's have a studentNumber that must be set.  The studentNumber is unique to all students in the district account and can't be null.

>### Student Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**createdDate**|string||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**dateOfBirth**|string|||yes|null &#124; yyyy-MM-dd|
>|**economicallyDisadvantaged**|string|||yes|null &#124; true &#124; false|
>|**elaDevelopmentalLevel**|int|||yes|null &#124; 0-12|
>|**englishLanguageLearner**|string|||yes|null &#124; true &#124; false|
>|**ethnicityId**|string|||yes|Enter '01' for American Indian, Native American, or Alaska native; '02' for Asian; <BR/>'03' for black or African American; '04' for Hispanic, Latino, or Hispanic Latino;<BR/> '05' for white or Caucasian; '06' for Native Hawaiian or Other Pacific Islander; '07' for two or more races.|
>|**firstName**|string|||no|string, length 50|
>|**gender**|string|||yes|null &#124; male &#124; female|
>|**gradeLevel**|int|||no|0-12|
>|**id**|string|globally|read-only|no|string, length 32|
>|**lastLoginDate**|date||read-only|yes|null &#124; yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**lastName**|string|||no|string, length 50|
>|**mathDevelopmentalLevel**|int|||yes|null &#124; 0-12|
>|**migrant**|string|||yes|null &#124; true &#124; false|
>|**ownerId**|string|within district||yes|null &#124; string, length 64|
>|**partnerId**|string|within district||yes|null &#124; string, length 64|
>|**password**|string||*write-only*|no|string, length 4-24 - setting null on update leaves the password unchanged|
>|**specialEducation**|string|||yes|null &#124; true &#124; false|
>|**studentId**|string|within district||no|string, length 50|
>|**userName**|string|within state||no|string, length 50|
>|_**classes**_|link||read-only|no||
>|_**school**_|link||create-time|no||
>|_**self**_|link|globally|read-only|no||

--
Get all of the students related to an i-Ready account.
GET /api/v1/students{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/students?limit=2&offset=0"}
            "next": { "href": "/api/v1/students?limit=2&offset=2"}
        },
        "items": [
            {
                "id": "{first-student-id}",
                "firstName": "Rick",
                "lastName": "Campbell",
                "userName": "di-rcampbell@oh",
                "studentId": "e250345c39b7",
                "ownerId": null,
                "partnerId": null,
                "dateOfBirth": null,
                "gradeLevel": "5",
                "mathDevelopmentalLevel": null,
                "elaDevelopmentalLevel": null,
                "englishLanguageLearner": "false",
                "specialEducation": "false",
                "economicallyDisadvantaged": "false",
                "migrant": "false",
                "gender": null,
                "ethnicityId": "05",
                "createdDate": "2012-11-29T14:56:43Z",
                "lastLoginDate": "2013-02-13T14:26:17Z",
                "_links":
                {
                   "school": { "href": "/api/v1/schools/{first-school-id}" },
                   "self": { "href": "/api/v1/students/{first-student-id}" },
                   "classes": { "href": "/api/v1/students/{first-student-id}/classes" }
                }
            },
            {
                "id": "{second-student-id}",
                "firstName": "Hosea",
                "lastName": "Alvarez",
                "userName": "di-halvarez@oh",
                "studentId": "2d7b7295efd3",
                "ownerId": null,
                "partnerId": null,
                "dateOfBirth": null,
                "gradeLevel": "2",
                "mathDevelopmentalLevel": null,
                "elaDevelopmentalLevel": null,
                "englishLanguageLearner": "false",
                "specialEducation": "false",
                "economicallyDisadvantaged": "false",
                "migrant": "false",
                "gender": null,
                "ethnicityId": "01",
                "createdDate": "2012-11-29T14:56:43Z",
                "lastLoginDate": null,
                "_links":
                {
                   "school": { "href": "/api/v1/schools/{second-school-id}" },
                   "self": { "href": "/api/v1/students/{second-student-id}" },
                   "classes": { "href": "/api/v1/students/{second-student-id}/classes" }
                }
           }
       ]
    }
}

Create a new Student.

Read-only properties will be ignored.
POST /api/v1/students
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{
    "id": null,
    "firstName": "Hosea",
    "lastName": "Alvarez",
    "userName": "di-halvarez@oh",
    "studentId": "2d7b7295efd3",
    "ownerId": null,
    "partnerId": null,
    "dateOfBirth": null,
    "gradeLevel": "2",
    "mathDevelopmentalLevel": null,
    "elaDevelopmentalLevel": null,
    "englishLanguageLearner": "false",
    "specialEducation": "false",
    "economicallyDisadvantaged": "false",
    "migrant": "false",
    "gender": null,
    "ethnicityId": "01",
    "password": "secret",
    "createdDate": null,
    "lastLoginDate": null,
    "_links":
    {
        "school": { "href": "/api/v1/schools/{school-id}" },
        "self": null,
        "classes": null
    }
}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{id}",
        "firstName": "Hosea",
        "lastName": "Alvarez",
        "userName": "di-halvarez@oh",
        "studentId": "2d7b7295efd3",
        "ownerId": null,
        "partnerId": null,
        "dateOfBirth": null,
        "gradeLevel": "2",
        "mathDevelopmentalLevel": null,
        "elaDevelopmentalLevel": null,
        "englishLanguageLearner": "false",
        "specialEducation": "false",
        "economicallyDisadvantaged": "false",
        "migrant": "false",
        "gender": null,
        "ethnicityId": "01",
        "createdDate": "2012-11-31T10:32:43Z",
        "lastLoginDate": null,
        "_links":
        {
           "school": { "href": "/api/v1/schools/{school-id}" },
           "self": { "href": "/api/v1/students/{id}" },
           "classes": { "href": "/api/v1/students/{id}/classes" }
        }
    }
}

Get the details of a particular Student.
GET /api/v1/students/{id}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{id}",
        "firstName": "Hosea",
        "lastName": "Alvarez",
        "userName": "di-halvarez@oh",
        "studentId": "2d7b7295efd3",
        "ownerId": null,
        "partnerId": null,
        "dateOfBirth": null,
        "gradeLevel": "2",
        "mathDevelopmentalLevel": null,
        "elaDevelopmentalLevel": null,
        "englishLanguageLearner": "false",
        "specialEducation": "false",
        "economicallyDisadvantaged": "false",
        "migrant": "false",
        "gender": null,
        "ethnicityId": "01",
        "createdDate": "2012-11-29T14:56:43Z",
        "lastLoginDate": null,
        "_links":
        {
            "school": { "href": "/api/v1/schools/{school-id}" },
            "self": { "href": "/api/v1/students/{id}" },
            "classes": { "href": "/api/v1/students/{id}/classes" }
        }
    }
}

Update a particular student resource.

Read-only properties will be ignored.
PUT /api/v1/students/{id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{
    "id": "{id}",
    "firstName": "Hosea",
    "lastName": "Alvarez",
    "userName": "di-halvarez@oh",
    "studentId": "2d7b7295efd3",
    "ownerId": null,
    "partnerId": null,
    "dateOfBirth": null,
    "gradeLevel": "2",
    "mathDevelopmentalLevel": null,
    "elaDevelopmentalLevel": null,
    "englishLanguageLearner": "false",
    "specialEducation": "false",
    "economicallyDisadvantaged": "false",
    "migrant": "false",
    "gender": null,
    "ethnicityId": "01",
    "password": "newSecret",
    "createdDate": "2012-11-29T14:56:43Z",
    "lastLoginDate": null,
    "_links":
    {
        "school": { "href": "/api/v1/schools/{school-id}" },
        "self": { "href": "/api/v1/students/{id}" },
        "classes": { "href": "/api/v1/students/{id}/classes" }
    }
}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{id}",
        "firstName": "Hosea",
        "lastName": "Alvarez",
        "userName": "di-halvarez@oh",
        "studentId": "2d7b7295efd3",
        "ownerId": null,
        "partnerId": null,
        "dateOfBirth": null,
        "gradeLevel": "2",
        "mathDevelopmentalLevel": null,
        "elaDevelopmentalLevel": null,
        "englishLanguageLearner": "false",
        "specialEducation": "false",
        "economicallyDisadvantaged": "false",
        "migrant": "false",
        "gender": null,
        "ethnicityId": "01",
        "createdDate": "2012-12-03T16:02:43Z",
        "lastLoginDate": null,
        "_links":
        {
            "school": { "href": "/api/v1/schools/{school-id}" },
            "self": { "href": "/api/v1/students/{id}" },
            "classes": { "href": "/api/v1/students/{id}/classes" }
        }
    }
}

Deleting of student resources is supported only for student accounts that have not been used yet and are not assigned to any classes.  Student accounts that have not been used will have lastLoginDate set to null.
DELETE /api/v1/students/{id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 405
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    }
}

--
Student/Class Resources
The following is a section of resources related to i-Ready Student/Class relationship resources.

>### Class/Student Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**createdDate**|date||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**id**|string|globally|read-only|no|string, length 32|
>|**ownerId**|string|within district||yes|null &#124; string, length 64|
>|**partnerId**|string|within district||yes|null &#124; string, length 64|
>|_**student**_|link||create-time|no||
>|_**class**_|link||create-time|no||
>|_**self**_|link|globally|read-only|no||

> Note: The relationship resources within the /api/v1/students/{student-id}/classes collection will typically be stored at the path /api/v1/classes/{class-id}/students/{relationship-id}.  For accurate consumption of a resource the 'self' link should be utilized to directly access the relationship resource.

> Creation of new relationships can be done via a POST to the students/{student-id}/classes collection however the new relationship item created will have a URI fo the form classes/{class-id}/students/{relationship-id}.
--
Retrieve the classes assigned to a particular student.
GET /api/v1/students/{id}/classes{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/students/{id}/classes?limit=2"}
            "next": { "href": "/api/v1/students/{id}/classes?limit=2&offset=2"}
        },
        "items": [
            {
                "id": "{first-relationship-id}",
                "ownerId": null,
                "partnerId": null,
                "createdDate": "2012-12-03T16:02:43Z",
                "_links": {
                    "self": { "href": "/api/v1/classes/{first-relationship-id}/students/{id}"}
                    "student": { "href": "/api/v1/students/{id}"}
                    "class": { "href": "/api/v1/classes/{first-class-id}"}
                }
            },
            {
                "id": "{second-relationship-id}",
                "ownerId": null,
                "partnerId": null,
                "createdDate": "2012-12-03T16:02:43Z",
                "_links": {
                    "self": { "href": "classes/{second-relationship-id}/students/{id}/"}
                    "student": { "href": "/api/v1/students/{id}"}
                    "class": { "href": "/api/v1/classes/{second-class-id}"}
                }
            }
        ]
    }
}

Creation of new student/class relationship.
POST /api/v1/students/{id}/classes
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{
    "id": null,
    "ownerId": null,
    "partnerId": null,
    "createdDate": null,
    "_links": {
        "self": null
        "student": { "href": "/api/v1/students/{id}"}
        "class": { "href": "/api/v1/classes/{class-id}"}
    }
}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{relationship-id}",
        "ownerId": null,
        "partnerId": null,
        "createdDate": "2012-12-03T16:02:43Z",
        "_links": {
            "self": { "href": "/api/v1/classes/{relationship-id}/students/{id}"}
            "student": { "href": "/api/v1/students/{id}"}
            "class": { "href": "/api/v1/classes/{class-id}"}
        }
    }
}

Retrieve a particular student/class relationship.

This is not the proper path to access student/class relationship objects.  See the [Class/Student Resources](http://docs.cainc.apiary.io/#classstudent resources) section for the proper path to use. 
GET /api/v1/students/{id}/classes/{relationship-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 404
< Content-Type: application/json
{
    "status": {
        "httpCode": "404",
        "errorId": "C10003",
        "userMessage": "The requested resource was not found.",
        "detailsMessage": "No resources are available at this URI.",
        "apiVersion": "v1"
    }
}

Updating of student/class relationships is not supported.  If a student changes classes the old relationship should be deleted and a new one added.

This is not the proper path to access student/class relationship objects.  See the [Class/Student Resources](http://docs.cainc.apiary.io/#classstudent resources) section for the proper path to use.
PUT /api/v1/students/{id}/classes/{relationship-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 404
< Content-Type: application/json
{
    "status": {
        "httpCode": "404",
        "errorId": "C10003",
        "userMessage": "The requested resource was not found.",
        "detailsMessage": "No resources are available at this URI.",
        "apiVersion": "v1"
    }
}

Delete a particular student/class relationship.

This is not the proper path to access student/class relationship objects.  See the [Class/Student Resources](http://docs.cainc.apiary.io/#classstudent resources) section for the proper path to use.
DELETE /api/v1/students/{id}/classes/{relationship-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 404
< Content-Type: application/json
{
    "status": {
        "httpCode": "404",
        "errorId": "C10003",
        "userMessage": "The requested resource was not found.",
        "detailsMessage": "No resources are available at this URI.",
        "apiVersion": "v1"
    }
}


--
Teacher Resources
The following is a section of resources related to i-Ready Teacher resources.

Teachers are identified by their userName. The teacher's userName must by unique to all users within their distict account's state.

>### Teacher Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**createdDate**|date||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**emailAddress**|string|||yes|null &#124; string, length 100<BR/>requires a properly formated e-mail address|
>|**firstName**|string|||no|string, length 50|
>|**id**|string|globally|read-only|no|string, length 32|
>|**lastLoginDate**|date||read-only|yes|null &#124; yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**lastName**|string|||no|string, length 50|
>|**ownerId**|string|within district||yes|null &#124; string, length 64|
>|**partnerId**|string|within district||yes|null &#124; string, length 64|
>|**password**|string||*write-only*|no|string, length 4-24 - setting null on update leaves the password unchanged|
>|**userName**|string|within state||no|string, length 50|
>|_**classes**_|link||read-only|no||
>|_**school**_|link||create-time|no||
>|_**self**_|link|globally|read-only|no||

--
Get all of the teachers related to an i-Ready account.
GET /api/v1/teachers{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/teachers?limit=2&offset=0"}
            "next": { "href": "/api/v1/teachers?limit=2&offset=2"}
        },
        "items": [
            {
                "id": "{first-teacher-id}",
                "firstName": "Janet",
                "lastName": "Benjamin",
                "userName": "DI-JBenjamin",
                "ownerId": null,
                "partnerId": null,
                "emailAddress": null,
                "createdDate": "2012-11-29T14:56:43Z",
                "lastLoginDate": "2013-01-29T09:56:43Z",
                "_links":
                {
                   "school": { "href": "/api/v1/schools/{first-school-id}" },
                   "self": { "href": "/api/v1/teachers/{first-teacher-id}" },
                   "classes": { "href": "/api/v1/teachers/{first-teacher-id}/classes" }
                }
            },
            {
                "id": "{first-teacher-id}",
                "firstName": "Michael",
                "lastName": "Williams",
                "userName": "DI-MWilliams",
                "ownerId": null,
                "partnerId": null,
                "emailAddress": null,
                "createdDate": "2012-11-29T14:56:43Z",
                "lastLoginDate": null,
                "_links":
                {
                   "school": { "href": "/api/v1/schools/{second-school-id}" },
                   "self": { "href": "/api/v1/teachers/{second-teacher-id}" },
                   "classes": { "href": "/api/v1/teachers/{second-teacher-id}/classes" }
                }
            }
       ]
    }
}

Create a new Teacher.

Read-only properties will be ignored.
POST /api/v1/teachers
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{
    "id": null,
    "firstName": "Janet",
    "lastName": "Benjamin",
    "userName": "DI-JBenjamin",
    "ownerId": null,
    "partnerId": null,
    "emailAddress": null,
    "password": "myPassword",
    "createdDate": null,
    "lastLoginDate": "2013-01-29T09:56:43Z",
    "_links":
    {
       "school": { "href": "/api/v1/schools/{school-id}" },
       "self": null,
       "classes": null
    }
}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{id}",
        "firstName": "Janet",
        "lastName": "Benjamin",
        "userName": "DI-JBenjamin",
        "ownerId": null,
        "partnerId": null,
        "emailAddress": null,
        "createdDate": "2012-11-29T14:56:43Z",
        "lastLoginDate": "2013-01-29T09:56:43Z",
        "_links":
        {
           "school": { "href": "/api/v1/schools/{school-id}" },
           "self": { "href": "/api/v1/teachers/{id}" },
           "classes": { "href": "/api/v1/teachers/{id}/classes" }
        }
    }
}

Get the details of a particular Teacher.
GET /api/v1/teachers/{id}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{id}",
        "firstName": "Janet",
        "lastName": "Benjamin",
        "userName": "DI-JBenjamin",
        "ownerId": null,
        "partnerId": null,
        "emailAddress": null,
        "createdDate": "2012-11-29T14:56:43Z",
        "lastLoginDate": "2013-01-29T09:56:43Z",
        "_links":
        {
           "school": { "href": "/api/v1/schools/{school-id}" },
           "self": { "href": "/api/v1/teachers/{id}" },
           "classes": { "href": "/api/v1/teachers/{id}/classes" }
        }
    }
}

Update a particular teacher resource.

Read-only properties will be ignored.
PUT /api/v1/teachers/{id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{
    "id": "{id}",
    "firstName": "Janet",
    "lastName": "Benjamin",
    "userName": "DI-JBenjamin",
    "ownerId": null,
    "partnerId": null,
    "emailAddress": null,
    "password": "myNewPassword",
    "createdDate": "2012-11-29T14:56:43Z",
    "lastLoginDate": "2013-01-29T09:56:43Z",
    "_links":
    {
       "school": { "href": "/api/v1/schools/{school-id}" },
       "self": { "href": "/api/v1/teachers/{id}" },
       "classes": { "href": "/api/v1/teachers/{id}/classes" }
    }
}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{id}",
        "firstName": "Janet",
        "lastName": "Benjamin",
        "userName": "DI-JBenjamin",
        "ownerId": null,
        "partnerId": null,
        "emailAddress": null,
        "createdDate": "2012-11-29T14:56:43Z",
        "lastLoginDate": "2013-01-29T09:56:43Z",
        "_links":
        {
           "school": { "href": "/api/v1/schools/{school-id}" },
           "self": { "href": "/api/v1/teachers/{id}" },
           "classes": { "href": "/api/v1/teachers/{id}/classes" }
        }
    }
}

Deleting of teacher resources is supported only for teacher accounts that have not been used yet and are not assigned to any classes.  Teacher accounts that have not been used will have lastLoginDate set to null.
DELETE /api/v1/teachers/{id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    }
}

--
Teacher/Class Resources
The following is a section of resources related to i-Ready Teacher/Class relationship resources.

>### Class/Teacher Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**createdDate**|date||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**id**|string|globally|read-only|no|string, length 32|
>|**ownerId**|string|within district||yes|null &#124; string, length 64|
>|**partnerId**|string|within district||yes|null &#124; string, length 64|
>|_**teacher**_|link||create-time|no||
>|_**class**_|link||create-time|no||
>|_**self**_|link|globally|read-only|no||

> Note: The relationship resources within the /api/v1/teachers/{teacher-id}/classes collection will typically be stored at the path /api/v1/classes/{class-id}/teachers/{relationship-id}.  For accurate consumption of a resource the 'self' link should be utilized to directly access the relationship resource.

> Creation of new relationships can be done via a POST to the teachers/{teacher-id}/classes collection however the new relationship item created will have a URI fo the form classes/{class-id}/teachers/{relationship-id}.
--
Retrieve the classes assigned to a particular teacher.
GET /api/v1/teachers/{id}/classes{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/teachers/{id}/classes?limit=2"}
            "next": { "href": "/api/v1/teachers/{id}/classes?limit=2&offset=2"}
        },
        "items": [
            {
                "id": "{first-relationship-id}",
                "ownerId": null,
                "partnerId": null,
                "createdDate": "2012-12-03T16:02:43Z",
                "_links": {
                    "self": { "href": "/api/v1/classes/{first-relationship-id}/teachers/{id}"}
                    "teacher": { "href": "/api/v1/teachers/{id}"}
                    "class": { "href": "/api/v1/classes/{first-class-id}"}
                }
            },
            {
                "id": "{second-relationship-id}",
                "ownerId": null,
                "partnerId": null,
                "createdDate": "2012-12-03T16:02:43Z",
                "_links": {
                    "self": { "href": "classes/{second-relationship-id}/teachers/{id}/"}
                    "teacher": { "href": "/api/v1/teachers/{id}"}
                    "class": { "href": "/api/v1/classes/{second-class-id}"}
                }
            }
        ]
    }
}

Creation of new teacher/class relationship.
POST /api/v1/teachers/{id}/classes
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{
    "id": null,
    "ownerId": null,
    "partnerId": null,
    "createdDate": null,
    "_links": {
        "self": null
        "teacher": { "href": "/api/v1/teachers/{id}"}
        "class": { "href": "/api/v1/classes/{class-id}"}
    }
}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{relationship-id}",
        "ownerId": null,
        "partnerId": null,
        "createdDate": "2012-12-03T16:02:43Z",
        "_links": {
            "self": { "href": "/api/v1/classes/{relationship-id}/teachers/{id}"}
            "teacher": { "href": "/api/v1/teachers/{id}"}
            "class": { "href": "/api/v1/classes/{class-id}"}
        }
    }
}

This is not the proper path to access teacher/class relationship objects.  To retrieve teacher/class relationship see the [Class/Teacher Resources](http://docs.cainc.apiary.io/#classteacher resources) section for the proper path to use. 
GET /api/v1/teachers/{id}/classes/{relationship-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 404
< Content-Type: application/json
{
    "status": {
        "httpCode": "404",
        "errorId": "C10003",
        "userMessage": "The requested resource was not found.",
        "detailsMessage": "No resources are available at this URI.",
        "apiVersion": "v1"
    }
}

Updating of teacher/class relationships is not supported.  If a teacher changes classes the old relationship should be deleted and a new one added.

This is not the proper path to access teacher/class relationship objects.  See the [Class/Teacher Resources](http://docs.cainc.apiary.io/#classteacher resources) section for the proper path to use.
PUT /api/v1/teachers/{id}/classes/{relationship-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 404
< Content-Type: application/json
{
    "status": {
        "httpCode": "404",
        "errorId": "C10003",
        "userMessage": "The requested resource was not found.",
        "detailsMessage": "No resources are available at this URI.",
        "apiVersion": "v1"
    }
}

This is not the proper path to access teacher/class relationship objects.  To delete teacher/class relationship see the [Class/Teacher Resources](http://docs.cainc.apiary.io/#classteacher resources) section for the proper path to use.
DELETE /api/v1/teachers/{id}/classes/{relationship-id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 404
< Content-Type: application/json
{
    "status": {
        "httpCode": "404",
        "errorId": "C10003",
        "userMessage": "The requested resource was not found.",
        "detailsMessage": "No resources are available at this URI.",
        "apiVersion": "v1"
    }
}

--
Administrator Resources
 >**Administrator related resources have been removed from the initial release of the i-Ready APIs**
 
The following is a section of resources related to i-Ready Administrator resources.

Administrators are identified by their userName. The administrator's userName must by unique to all users within their distict account's state.

>### Administrator Properties
>|Name|Type|Unique|Modifiable|Nullable|Valid Values|
>|--------|------|--------|-----------|-----------|----------------|
>|**createdDate**|date||read-only|no|yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**emailAddress**|string|||yes|null &#124; string, length 100<BR/>requires a properly formated e-mail address|
>|**firstName**|string|||no|string, length 50|
>|**id**|string|globally|read-only|no|string, length 32|
>|**lastLoginDate**|date||read-only|yes|null &#124; yyyy-MM-dd'T'kk:mm:ss'Z' - Universal Sortable Date Time|
>|**lastName**|string|||no|string, length 50|
>|**ownerId**|string|within district||yes|null &#124; string, length 64|
>|**partnerId**|string|within district||yes|null &#124; string, length 64|
>|**password**|string||*write-only*|no|string, length 4-24 - setting null on update leaves the password unchanged|
>|**userName**|string|within state||no|string, length 50|
>|_**school**_|link||create-time|no||
>|_**self**_|link|globally|read-only|no||

--
Get all of the administrators related to an i-Ready account.
GET /api/v1/administrators{?limit,offset}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "limit": 2,
        "offset": 0,
        "_links": {
            "self": { "href": "/api/v1/administrators?limit=2&offset=0"},
            "next": { "href": "/api/v1/administrators?limit=2&offset=2"}
        },
        "items": [
            {
                "id": "{first-administrator-id}",
                "firstName": "Janet",
                "lastName": "Benjamin",
                "userName": "DI-JBenjamin",
                "ownerId": null,
                "partnerId": null,
                "emailAddress": null,
                "createdDate": "2012-11-29T14:56:43Z",
                "lastLoginDate": "2013-01-29T09:56:43Z",
                "_links":
                {
                   "school": { "href": "/api/v1/schools/{first-school-id}" },
                   "self": { "href": "/api/v1/administrators/{first-administrator-id}" }
                }
            },
            {
                "id": "{first-administrator-id}",
                "firstName": "Michael",
                "lastName": "Williams",
                "userName": "DI-MWilliams",
                "ownerId": null,
                "partnerId": null,
                "emailAddress": null,
                "createdDate": "2012-11-29T14:56:43Z",
                "lastLoginDate": null,
                "_links":
                {
                   "school": { "href": "/api/v1/schools/{second-school-id}" },
                   "self": { "href": "/api/v1/administrators/{second-administrator-id}" }
                }
            }
       ]
    }
}

Create a new Administrator.

Read-only properties will be ignored.
POST /api/v1/administrators
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{
    "id": null,
    "firstName": "Janet",
    "lastName": "Benjamin",
    "userName": "DI-JBenjamin",
    "externalId": null,
    "emailAddress": null,
    "password": "myAdminPassword",
    "createdDate": null,
    "lastLoginDate": "2013-01-29T09:56:43Z",
    "_links":
    {
       "school": { "href": "/api/v1/schools/{school-id}" },
       "self": null,
       "administrators": null
    }
}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{id}",
        "firstName": "Janet",
        "lastName": "Benjamin",
        "userName": "DI-JBenjamin",
        "ownerId": null,
        "partnerId": null,
        "emailAddress": null,
        "createdDate": "2012-11-29T14:56:43Z",
        "lastLoginDate": "2013-01-29T09:56:43Z",
        "_links":
        {
           "school": { "href": "/api/v1/schools/{school-id}" },
           "self": { "href": "/api/v1/administrators/{id}" }
        }
    }
}

Get the details of a particular Administrator.
GET /api/v1/administrators/{id}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{id}",
        "firstName": "Janet",
        "lastName": "Benjamin",
        "userName": "DI-JBenjamin",
        "ownerId": null,
        "partnerId": null,
        "emailAddress": null,
        "createdDate": "2012-11-29T14:56:43Z",
        "lastLoginDate": "2013-01-29T09:56:43Z",
        "_links":
        {
           "school": { "href": "/api/v1/schools/{school-id}" },
           "self": { "href": "/api/v1/administrators/{id}" }
        }
    }
}

Update a particular administrator resource.

Read-only properties will be ignored.
PUT /api/v1/administrators/{id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{
    "id": "{id}",
    "firstName": "Janet",
    "lastName": "Benjamin",
    "userName": "DI-JBenjamin",
    "ownerId": null,
    "partnerId": null,
    "emailAddress": null,
    "password": "myUpdatedPassword",
    "createdDate": "2012-11-29T14:56:43Z",
    "lastLoginDate": "2013-01-29T09:56:43Z",
    "_links":
    {
       "school": { "href": "/api/v1/schools/{school-id}" },
       "self": { "href": "/api/v1/administrators/{id}" }
    }
}
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    },
    "data": {
        "id": "{id}",
        "firstName": "Janet",
        "lastName": "Benjamin",
        "userName": "DI-JBenjamin",
        "ownerId": null,
        "partnerId": null,
        "emailAddress": null,
        "createdDate": "2012-11-29T14:56:43Z",
        "lastLoginDate": "2013-01-29T09:56:43Z",
        "_links":
        {
           "school": { "href": "/api/v1/schools/{school-id}" },
           "self": { "href": "/api/v1/administrators/{id}" },
        }
    }
}

Deleting of administrator resources is supported only for administrator accounts that have not been used yet.
Administrator accounts that have not been used will have lastLoginDate set to null.
DELETE /api/v1/administrators/{id}
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
< 200
< Content-Type: application/json
{
    "status": {
        "httpCode": "200",
        "errorId": "C00000",
        "userMessage": "Success",
        "detailsMessage": "Success",
        "apiVersion": "v1"
    }
}


--
Error Handling
The i-Ready APIs return, when possible, error details in json.

>### Error Types
>|Error Code|HTTP Code|User Message|Details Message|Properties|
>|--------------------|-----------|--------------|--------------|-----------|
>|SUCCESS|200|Success|Success||
>|*Request Validation Errors*|||||
>|NO_OBJECT_FOUND|404|The requested entity was not found.|No entity with the id {value} was found.|value|
>|INVALID_PARAMETER_VALUE|400|The request included an invalid parameter value.|The value {value} is invalid for the parameter {property}.|value, property|
>|UNIQUENESS_VALIDATION_FAILURE|409|The request included an invalid parameter value.|The value {value} is invalid for the parameter {property} based on system uniqueness validation rules.|value, property|
>|PATH_BODY_VALIDATION_FAILURE|400|The data in the URI path has a mismatch with data in the request body.|The value {value} is invalid for the parameter {property} for the given API request URI.|value, property|
>|REQUESTED_RELATIONSHIP_ALREADY_EXISTS|400|The requested operation is not supported as the relationship already exists.|The requested operation is not supported as the relationship already exists.||
>|CLASS_ADD_NOT_ALLOWED_FOR_USER|403|Request to add the user to a new class cannot be done.|The class value {value} was provided to add the user to a new class. This cannot be done because the user is already enrolled in a matching class. Remove the student from the current matching class to change enrollment.||
>|SCHOOL_MOVE_NOT_ALLOWED_FOR_USER|403|Request to move the user to a new school cannot be done.|The school value {value} was provided to move the user to a new school. This cannot be done.||
>|*Invalid JSON Errors*|||||
>|INVALID_JSON|400|The request included invalid data.|There was an error parsing the JSON. {details} - Line {rowNumber} Column {columnNumber}|details, rowNumber, columnNumber|
>|INVALID_JSON_PROPERTY|400|The request included an invalid property.|An unknown property {value} was included in the supplied json.|value|
>|*Invalid Operation Errors*|||||
>|INVALID_VERB_FOR_RESOURCE|405|The resource doesn't support the request.|The resource doesn't support HTTP {httpVerb} requests.|httpVerb|
>|APPLICATION_ACTION_NOT_ALLOWED|400|Based on permitted application logic, the requested operation is not supported for an entity in this state.|Based on permitted application logic, the resource cannot be modified in the requested manner.||
>|*Generic Error Codes*|||||
>|UNHANDLED_ERROR|400|An unknown error occurred.|An unknown error occurred.||
>|UNKNOWN_ERROR|500|An unknown error occurred.|Unknown error with id {internalId} and Parameters {data}.|internalId, data|
>|UNKNOWN_APPLICATION_ERROR|500|An unknown error occurred in the application.|An unknown error occurred in the application.||

--
GET /api/v1/{resource}     - NO_OBJECT_FOUND
< 404
< Content-Type: application/json
/* This error occurs when the {id} value does not match any resources on the server. */
{
    "httpCode":"404",
    "errorId":"NO_OBJECT_FOUND",
    "userMessage":"The requested entity was not found.",
    "detailsMessage":"No entity with the id {id} was found. Entity not found for id {id}.",
    "parameters": {
        "value":"{id}"
    },
    "exceptionString":"",
    "apiVersion":"v1"
}

PUT /api/v1/{collection}/{id}    - INVALID_PARAMETER_VALUE
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{ ... }
< 404
< Content-Type: application/json
/* This error will occur when an invalid parameter is specified on create.  For example if the id value is specified in a PUT request. */
{
    "httpCode": "400",
    "errorId": "INVALID_PARAMETER_VALUE",
    "userMessage": "The request included an invalid parameter value.",
    "detailsMessage": "The value {invalid-value} is invalid for the parameter {property-name}.",
    "parameters": {
        "value": "{invalid-value}",
        "property": "{property-name}"
    },
    "apiVersion": "v1"
}


POST /api/v1/{collection}/{id}    - INVALID_PARAMETER_VALUE
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{ ... }
< 404
< Content-Type: application/json
/* This error will occur when an invalid parameter is specified on create.  For example if the id value is specified in a PUT request. */
{
    "httpCode": "400",
    "errorId": "INVALID_PARAMETER_VALUE",
    "userMessage": "The request included an invalid parameter value.",
    "detailsMessage": "The value {invalid-value} is invalid for the parameter {property-name}.",
    "parameters": {
        "value": "{invalid-value}",
        "property": "{property-name}"
    },
    "apiVersion": "v1"
}

PUT /api/v1/{collection}/{id}    - UNIQUENESS_VALIDATION_FAILURE
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{ ... }
< 409
< Content-Type: application/json
/* This error will occur when the json in a create request has property values that fail to meet their uniqueness criteria.  In this example a value of the name property conflicts with an existing object. */
/* For uniqueness rules that involve more than one property the system will return details about one of the properties involved.  For a given uniqueness constraint the details will always report on the same property. */
{
    "httpCode": "409",
    "errorId": "UNIQUENESS_VALIDATION_FAILURE",
    "userMessage": "The request included an invalid parameter value.",
    "detailsMessage": "The value Class Two is invalid for the parameter name based on system uniqueness validation rules. A class with this name (for the same school and product) already exists.",
    "parameters": {
        "value": "Class Two",
        "property": "name"
    },
    "apiVersion": "v1"
}

POST /api/v1/{collection}/{id}    - UNIQUENESS_VALIDATION_FAILURE
> Authorization: Basic REktQWRtaW4yOnBhc3N3b3JkMg==
> Content-Type: application/json
{ ... }
< 409
< Content-Type: application/json
/* This error will occur when the json in a create request has property values that fail to meet their uniqueness criteria.  In this example a value of the name property conflicts with an existing object. */
/* For uniqueness rules that involve more than one property the system will return details about one of the properties involved.  For a given uniqueness constraint the details will always report on the same property. */
{
    "httpCode": "409",
    "errorId": "UNIQUENESS_VALIDATION_FAILURE",
    "userMessage": "The request included an invalid parameter value.",
    "detailsMessage": "The value Class Two is invalid for the parameter name based on system uniqueness validation rules. A class with this name (for the same school and product) already exists.",
    "parameters": {
        "value": "Class Two",
        "property": "name"
    },
    "apiVersion": "v1"
}

GET /api/v1/{resource}     - INVALID_VERB_FOR_RESOURCE
< 405
< Content-Type: application/json
/* This error will occur when the an http request is made that isn’t supported by the resource specified.  */
 {
    "httpCode": "405",
    "errorId": "INVALID_VERB_FOR_RESOURCE",
    "userMessage": "The resource doesn't support the request.",
    "detailsMessage": "The resource doesn't support HTTP GET requests.",
    "apiVersion": "v1"
}

PUT /api/v1/{resource}     - INVALID_VERB_FOR_RESOURCE
< 405
< Content-Type: application/json
/* This error will occur when the an http request is made that isn’t supported by the resource specified.  */
 {
    "httpCode": "405",
    "errorId": "INVALID_VERB_FOR_RESOURCE",
    "userMessage": "The resource doesn't support the request.",
    "detailsMessage": "The resource doesn't support HTTP PUT requests.",
    "apiVersion": "v1"
}

POST /api/v1/{resource}     - INVALID_VERB_FOR_RESOURCE
< 405
< Content-Type: application/json
/* This error will occur when the an http request is made that isn’t supported by the resource specified.  */
 {
    "httpCode": "405",
    "errorId": "INVALID_VERB_FOR_RESOURCE",
    "userMessage": "The resource doesn't support the request.",
    "detailsMessage": "The resource doesn't support HTTP POST requests.",
    "apiVersion": "v1"
}

DELETE /api/v1/{resource}     - INVALID_VERB_FOR_RESOURCE
< 405
< Content-Type: application/json
/* This error will occur when the an http request is made that isn’t supported by the resource specified.  */
 {
    "httpCode": "405",
    "errorId": "INVALID_VERB_FOR_RESOURCE",
    "userMessage": "The resource doesn't support the request.",
    "detailsMessage": "The resource doesn't support HTTP DELETE requests.",
    "apiVersion": "v1"
}
